<a href="https://colab.research.google.com/github/MariaNikolaeva2028/LinearRegression/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Линейная регрессия. Представлены результаты наблюдений длительности нахождения человека в очереди в зависимости от количества людей в этой очереди. Необходимо вычислить:выборочное среднее Х, выборочное среднее Y, коэффициенты θ0 и θ1. Оценить точность модели.

In [8]:
import pandas as pd
import io
from sklearn.linear_model import LinearRegression
import numpy as np

Загрузка данных:

In [5]:
data = """id,X,Y
1,22,45
2,19,42
3,11,23
4,7,23
5,13,23
6,20,39
7,8,19
8,12,21
9,15,28
10,23,65"""
data = pd.read_csv(io.StringIO(data), index_col = 'id')
data

X   Y
id        
1   22  45
2   19  42
3   11  23
4    7  23
5   13  23
6   20  39
7    8  19
8   12  21
9   15  28
10  23  65

Определение выборочного среднего X и Y:


In [6]:
print(data.X.mean())
print(data.Y.mean())

15.0
32.8


Обучение модели линейной регрессии:

In [9]:
reg_model = LinearRegression().fit(pd.DataFrame(data.X), pd.DataFrame(data.Y))

Вывод коэффициентов θ0 и θ1:

In [12]:
reg_model.intercept_


array([-1.65945946])

In [13]:
reg_model.coef_

array([[2.2972973]])

Определение предсказания модели для тренировочных данных:

In [14]:
y_predicted = reg_model.predict(pd.DataFrame(data.X))
y_predicted

array([[48.88108108],
       [41.98918919],
       [23.61081081],
       [14.42162162],
       [28.20540541],
       [44.28648649],
       [16.71891892],
       [25.90810811],
       [32.8       ],
       [51.17837838]])

Оценка точности модели, поиск коэффициент детерминации.

In [15]:
from sklearn.metrics import r2_score
r2_score(pd.DataFrame(data.Y), y_predicted)

0.8012731648349212

Таким образом, точность предсказанной модели составляет 80%.